apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
  namespace: dev
spec:
  # type: NodePort # to connect from outside the cluster
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      # nodePort: 30080  # 30000â€“32767 (Kubernetes default).

